name: Build Android APK (Expo)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

           - name: Build APK
        working-directory: ./frontend
        run: |
          npx eas-cli project:init --non-interactive --force
          npx eas-cli build --platform android --profile preview --non-interactive --no-wait

